[workspace]
members = [
    "crates/*",
    "python/refix-engine",
]
default-members = [
    "crates/*",
]
resolver = "3"

[workspace.package]
authors = ["David Steiner <david@davidsteiner.dev>"]
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/refixhq/refix"
repository = "https://github.com/refixhq/refix"
keywords = ["fix", "fix-protocol", "fix-engine", "trading", "finance"]
categories = ["encoding", "parsing", "finance"]

[workspace.dependencies]
bytes = "1.12.1"
pyo3 = "0.29.0"
refix-message = { version = "0.1.0", path = "crates/refix-message" }
serde = "1.0.229"
