# @generated by refix codegen from toy.xml. Do not edit.
# fmt: off

import enum
from functools import cached_property
from typing import ClassVar

from refix import RawMessage
from refix.enums import Unrecognized, from_value


class OrdType(enum.StrEnum):
    MARKET = "1"
    LIMIT = "2"


class ExecInst(enum.StrEnum):
    NOT_HELD = "1"
    PARTICIPATE_DONT_INITIATE = "6"


class PartyRole(enum.IntEnum):
    EXECUTING_FIRM = 1
    CLIENT_ID = 3


class NewOrderSingle:
    MSG_TYPE: ClassVar[bytes] = b"D"

    def __init__(self, raw: RawMessage) -> None:
        self._raw = raw

    @property
    def raw(self) -> RawMessage:
        return self._raw

    @cached_property
    def cl_ord_id(self) -> str | None:
        return self._raw.get_str(11)

    @cached_property
    def order_qty(self) -> int | None:
        return self._raw.get_int(38)

    @cached_property
    def price_raw(self) -> bytes | None:
        return self._raw.get(44)

    @cached_property
    def ord_type(self) -> OrdType | Unrecognized[str] | None:
        value = self._raw.get_str(40)
        return None if value is None else from_value(OrdType, value)

    @cached_property
    def exec_inst(self) -> tuple[ExecInst | Unrecognized[str], ...] | None:
        values = self._raw.get_multiple_values(18)
        return None if values is None else tuple(from_value(ExecInst, value) for value in values)


class Logon:
    MSG_TYPE: ClassVar[bytes] = b"A"

    def __init__(self, raw: RawMessage) -> None:
        self._raw = raw

    @property
    def raw(self) -> RawMessage:
        return self._raw
