# @generated by refix codegen from toy.xml. Do not edit.
# fmt: off

from __future__ import annotations

import enum
from functools import cached_property
from typing import ClassVar

import refix
from refix import GroupTable, KnownTags, RawMessage
from refix.enums import Unrecognized, from_value


class OrdType(enum.StrEnum):
    MARKET = "1"
    LIMIT = "2"


class ExecInst(enum.StrEnum):
    NOT_HELD = "1"
    PARTICIPATE_DONT_INITIATE = "6"


class PartyRole(enum.IntEnum):
    EXECUTING_FIRM = 1
    CLIENT_ID = 3


class PtysSubGrp:
    TABLE: ClassVar[GroupTable] = GroupTable(802, 523, (523,), ())

    KNOWN_TAGS: ClassVar[KnownTags] = KnownTags((523,))

    class Instance:
        def __init__(self, scope: refix.Scope) -> None:
            self._scope = scope

        @property
        def raw(self) -> refix.Scope:
            return self._scope

        @cached_property
        def party_sub_id(self) -> str | None:
            return self._scope.get_str(523)


class Parties:
    TABLE: ClassVar[GroupTable] = GroupTable(453, 448, (448, 452, 802), (PtysSubGrp.TABLE,))

    KNOWN_TAGS: ClassVar[KnownTags] = KnownTags((448, 452, 523, 802))

    class Instance:
        def __init__(self, scope: refix.Scope) -> None:
            self._scope = scope

        @property
        def raw(self) -> refix.Scope:
            return self._scope

        @cached_property
        def party_id(self) -> str | None:
            return self._scope.get_str(448)

        @cached_property
        def party_role(self) -> PartyRole | Unrecognized[int] | None:
            value = self._scope.get_int(452)
            return None if value is None else from_value(PartyRole, value)

        @cached_property
        def ptys_sub_grp(self) -> tuple[PtysSubGrp.Instance, ...]:
            scopes = self._scope.get_group(PtysSubGrp.TABLE, Parties.KNOWN_TAGS)
            return () if scopes is None else tuple(PtysSubGrp.Instance(scope) for scope in scopes)


class NewOrderSingle:
    MSG_TYPE: ClassVar[bytes] = b"D"

    KNOWN_TAGS: ClassVar[KnownTags] = KnownTags((
        8, 9, 10, 11, 18, 34, 35, 38, 40, 44, 49, 52, 56, 89, 93, 448, 452, 453, 523, 627, 628, 802,
    ))

    def __init__(self, raw: RawMessage) -> None:
        self._raw = raw

    @property
    def raw(self) -> RawMessage:
        return self._raw

    @cached_property
    def cl_ord_id(self) -> str | None:
        return self._raw.get_str(11)

    @cached_property
    def parties(self) -> tuple[Parties.Instance, ...]:
        scopes = self._raw.get_group(Parties.TABLE, NewOrderSingle.KNOWN_TAGS)
        return () if scopes is None else tuple(Parties.Instance(scope) for scope in scopes)

    @cached_property
    def order_qty(self) -> int | None:
        return self._raw.get_int(38)

    @cached_property
    def price_raw(self) -> bytes | None:
        return self._raw.get(44)

    @cached_property
    def ord_type(self) -> OrdType | Unrecognized[str] | None:
        value = self._raw.get_str(40)
        return None if value is None else from_value(OrdType, value)

    @cached_property
    def exec_inst(self) -> tuple[ExecInst | Unrecognized[str], ...] | None:
        values = self._raw.get_multiple_values(18)
        return None if values is None else tuple(from_value(ExecInst, value) for value in values)


class Logon:
    MSG_TYPE: ClassVar[bytes] = b"A"

    KNOWN_TAGS: ClassVar[KnownTags] = KnownTags((
        8, 9, 10, 34, 35, 49, 52, 56, 89, 93, 372, 384, 627, 628,
    ))

    class MsgTypes:
        TABLE: ClassVar[GroupTable] = GroupTable(384, 372, (372,), ())

        KNOWN_TAGS: ClassVar[KnownTags] = KnownTags((372,))

        class Instance:
            def __init__(self, scope: refix.Scope) -> None:
                self._scope = scope

            @property
            def raw(self) -> refix.Scope:
                return self._scope

            @cached_property
            def ref_msg_type(self) -> str | None:
                return self._scope.get_str(372)

    def __init__(self, raw: RawMessage) -> None:
        self._raw = raw

    @property
    def raw(self) -> RawMessage:
        return self._raw

    @cached_property
    def msg_types(self) -> tuple[Logon.MsgTypes.Instance, ...]:
        scopes = self._raw.get_group(Logon.MsgTypes.TABLE, Logon.KNOWN_TAGS)
        return () if scopes is None else tuple(Logon.MsgTypes.Instance(scope) for scope in scopes)
