// @generated by refix-codegen from toy.xml. Do not edit.
#![cfg_attr(rustfmt, rustfmt::skip)]

use refix_message::{GroupTable, Instances, InvalidValue, KnownTags, RawMessage, Tag};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OrdType<'a> {
    Market,
    Limit,
    Unknown(&'a [u8]),
}

impl<'a> OrdType<'a> {
    pub fn from_bytes(bytes: &'a [u8]) -> Self {
        match bytes {
            b"1" => Self::Market,
            b"2" => Self::Limit,
            unknown => Self::Unknown(unknown),
        }
    }
}

pub struct NewOrderSingle(RawMessage);

impl NewOrderSingle {
    pub const MSG_TYPE: &[u8] = b"D";

    pub const KNOWN_TAGS: KnownTags<'static> = KnownTags::new(&[
        Tag(11), Tag(38), Tag(40), Tag(44), Tag(448), Tag(453),
    ]);

    pub fn from_raw(raw: RawMessage) -> Self {
        Self(raw)
    }

    pub fn raw(&self) -> &RawMessage {
        &self.0
    }

    pub fn cl_ord_id(&self) -> Result<Option<&str>, InvalidValue> {
        self.0.get_str(Tag(11))
    }

    pub fn order_qty(&self) -> Result<Option<i64>, InvalidValue> {
        self.0.get_int(Tag(38))
    }

    pub fn price_raw(&self) -> Option<&[u8]> {
        self.0.get(Tag(44))
    }

    pub fn ord_type(&self) -> Option<OrdType<'_>> {
        self.0.get(Tag(40)).map(OrdType::from_bytes)
    }

    pub fn party_ids(&self) -> Result<Instances<'_, new_order_single::party_ids::Instance<'_>>, InvalidValue> {
        self.0.get_group(&new_order_single::party_ids::TABLE, &Self::KNOWN_TAGS).map(Instances::from)
    }
}

pub mod new_order_single {
    pub mod party_ids {
        use super::super::*;

        pub const TABLE: GroupTable<'static> = GroupTable::new(
            Tag(453),
            Tag(448),
            &[Tag(448)],
            &[],
        );

        pub const KNOWN_TAGS: KnownTags<'static> = KnownTags::new(&[Tag(448)]);

        #[derive(Clone, Copy, Debug)]
        pub struct Instance<'a>(refix_message::Scope<'a>);

        impl<'a> From<refix_message::Scope<'a>> for Instance<'a> {
            fn from(scope: refix_message::Scope<'a>) -> Self {
                Self(scope)
            }
        }

        impl<'a> Instance<'a> {
            pub fn raw(&self) -> refix_message::Scope<'a> {
                self.0
            }

            pub fn party_id(&self) -> Result<Option<&'a str>, InvalidValue> {
                self.0.get_str(Tag(448))
            }
        }
    }
}
