// Generated by refix-codegen from toy.xml. Do not edit.
use refix_message::{InvalidValue, RawMessage};

pub struct NewOrderSingle(RawMessage);

impl NewOrderSingle {
    pub const MSG_TYPE: &[u8] = b"D";

    pub fn from_raw(raw: RawMessage) -> Self {
        Self(raw)
    }

    pub fn raw(&self) -> &RawMessage {
        &self.0
    }

    pub fn cl_ord_id(&self) -> Result<Option<&str>, InvalidValue> {
        self.0.get_str(11)
    }

    pub fn order_qty(&self) -> Result<Option<i64>, InvalidValue> {
        self.0.get_int(38)
    }

    pub fn price_raw(&self) -> Option<&[u8]> {
        self.0.get(44)
    }
}
