[package]
name = "refix-cli"
description = "Command-line tools for the ReFIX engine"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "refix"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
refix-codegen = { workspace = true }
refix-dictionary = { workspace = true }
