use crate::snake_case;
use refix_dictionary::{DataType, Dictionary, Field, Message};
use std::collections::HashMap;

pub fn generate(dictionary: &Dictionary, source: &str) -> Result<String, Error> {
    let fields_by_tag: HashMap<u32, &Field> = dictionary
        .fields
        .iter()
        .map(|field| (field.tag, field))
        .collect();
    let messages: Vec<String> = dictionary
        .messages
        .iter()
        .map(|message| emit_message(message, &fields_by_tag))
        .collect::<Result<Vec<_>, _>>()?;
    Ok(format!(
        "// Generated by refix-codegen from {source}. Do not edit.\nuse refix_message::RawMessage;\n\n{}",
        messages.join("\n")
    ))
}

fn emit_message(message: &Message, fields_by_tag: &HashMap<u32, &Field>) -> Result<String, Error> {
    let message_struct = emit_message_struct(message);
    let message_impl = emit_message_impl(message, fields_by_tag)?;
    Ok(format!("{message_struct}\n{message_impl}"))
}

fn emit_message_struct(message: &Message) -> String {
    format!("pub struct {}(RawMessage);\n", message.name)
}

fn emit_message_impl(
    message: &Message,
    fields_by_tag: &HashMap<u32, &Field>,
) -> Result<String, Error> {
    let fields = message
        .fields
        .iter()
        .map(|field_ref| {
            fields_by_tag
                .get(&field_ref.tag)
                .copied()
                .ok_or(Error::UnknownTag {
                    message: message.name.clone(),
                    tag: field_ref.tag,
                })
        })
        .collect::<Result<Vec<_>, _>>()?;
    let mut members = vec![
        format!(
            "    pub const MSG_TYPE: &[u8] = b\"{}\";\n",
            message.msg_type
        ),
        "    pub fn from_raw(raw: RawMessage) -> Self {\n        Self(raw)\n    }\n".to_owned(),
        "    pub fn raw(&self) -> &RawMessage {\n        &self.0\n    }\n".to_owned(),
    ];
    members.extend(fields.into_iter().map(emit_accessor));

    Ok(format!(
        "impl {} {{\n{}}}\n",
        message.name,
        members.join("\n")
    ))
}

fn emit_accessor(field: &Field) -> String {
    format!(
        "    pub fn {name}(&self) -> {rust_type} {{\n        self.0.get({tag})\n    }}\n",
        name = snake_case(&field.name),
        rust_type = data_type_to_rust_type(&field.data_type),
        tag = field.tag
    )
}

fn data_type_to_rust_type(data_type: &DataType) -> String {
    match data_type {
        DataType::String => "Result<Option<&str>, InvalidValue>".to_owned(),
        DataType::Int => "Result<Option<i64>, InvalidValue>".to_owned(),
        DataType::Other(_) => "Option<&[u8]>".to_owned(),
    }
}

#[derive(Debug)]
pub enum Error {
    UnknownTag { message: String, tag: u32 },
}
