mod error;
mod messages;
mod naming;

use refix_dictionary::{Dictionary, Field};
use std::collections::HashMap;

pub use error::Error;
use messages::emit_message;

pub fn generate(dictionary: &Dictionary, source: &str) -> Result<String, Error> {
    let fields_by_tag: HashMap<u32, &Field> = dictionary
        .fields
        .iter()
        .map(|field| (field.tag, field))
        .collect();
    let messages: Vec<String> = dictionary
        .messages
        .iter()
        .map(|message| emit_message(message, &fields_by_tag))
        .collect::<Result<Vec<_>, _>>()?;
    Ok(format!(
        "// Generated by refix-codegen from {source}. Do not edit.\nuse refix_message::{{InvalidValue, RawMessage}};\n\n{}",
        messages.join("\n")
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use naming::method_name;
    use refix_dictionary::{Category, DataType, FieldRef, Message, Protocol, Version};

    fn field(name: &str, tag: u32, data_type: DataType) -> Field {
        Field {
            name: name.to_owned(),
            tag,
            data_type,
            values: vec![],
        }
    }

    fn dictionary_of(messages: Vec<Message>, fields: Vec<Field>) -> Dictionary {
        Dictionary {
            version: Version {
                protocol: Protocol::Fix,
                major: 4,
                minor: 4,
                service_pack: 0,
            },
            messages,
            fields,
        }
    }

    #[test]
    fn generates_a_complete_module() {
        let dictionary = dictionary_of(
            vec![Message {
                name: "NewOrderSingle".to_owned(),
                msg_type: "D".to_owned(),
                fields: vec![
                    FieldRef {
                        tag: 11,
                        is_required: true,
                    },
                    FieldRef {
                        tag: 38,
                        is_required: false,
                    },
                    FieldRef {
                        tag: 44,
                        is_required: false,
                    },
                ],
                category: Category::App,
            }],
            vec![
                field("ClOrdID", 11, DataType::String),
                field("OrderQty", 38, DataType::Int),
                field("Price", 44, DataType::Other("PRICE".to_owned())),
            ],
        );

        let expected = r#"// Generated by refix-codegen from toy.xml. Do not edit.
use refix_message::{InvalidValue, RawMessage};

pub struct NewOrderSingle(RawMessage);

impl NewOrderSingle {
    pub const MSG_TYPE: &[u8] = b"D";

    pub fn from_raw(raw: RawMessage) -> Self {
        Self(raw)
    }

    pub fn raw(&self) -> &RawMessage {
        &self.0
    }

    pub fn cl_ord_id(&self) -> Result<Option<&str>, InvalidValue> {
        self.0.get_str(11)
    }

    pub fn order_qty(&self) -> Result<Option<i64>, InvalidValue> {
        self.0.get_int(38)
    }

    pub fn price_raw(&self) -> Option<&[u8]> {
        self.0.get(44)
    }
}
"#;

        assert_eq!(generate(&dictionary, "toy.xml").unwrap(), expected);
    }

    #[test]
    fn emits_messages_in_dictionary_order() {
        let dictionary = dictionary_of(
            vec![
                Message {
                    name: "Heartbeat".to_owned(),
                    msg_type: "0".to_owned(),
                    fields: vec![],
                    category: Category::Admin,
                },
                Message {
                    name: "TestRequest".to_owned(),
                    msg_type: "1".to_owned(),
                    fields: vec![],
                    category: Category::Admin,
                },
            ],
            vec![],
        );

        let generated = generate(&dictionary, "toy.xml").unwrap();

        let heartbeat = generated.find("pub struct Heartbeat").unwrap();
        let test_request = generated.find("pub struct TestRequest").unwrap();
        assert!(heartbeat < test_request);
    }

    #[test]
    fn a_reference_to_an_unknown_tag_is_an_error() {
        let dictionary = dictionary_of(
            vec![Message {
                name: "Heartbeat".to_owned(),
                msg_type: "0".to_owned(),
                fields: vec![FieldRef {
                    tag: 112,
                    is_required: false,
                }],
                category: Category::Admin,
            }],
            vec![],
        );

        assert_eq!(
            generate(&dictionary, "toy.xml").unwrap_err(),
            Error::UnknownTag {
                message: "Heartbeat".to_owned(),
                tag: 112,
            }
        );
    }

    #[test]
    fn method_names_are_snake_case() {
        let name = method_name(&field("ClOrdID", 11, DataType::String));
        assert_eq!(name.unwrap(), "cl_ord_id");
    }

    #[test]
    fn keyword_method_names_are_escaped() {
        let name = method_name(&field("Yield", 236, DataType::String));
        assert_eq!(name.unwrap(), "r#yield");
    }

    #[test]
    fn suffixed_raw_names_are_not_escaped() {
        let name = method_name(&field("Yield", 236, DataType::Other("PRICE".to_owned())));
        assert_eq!(name.unwrap(), "yield_raw");
    }

    #[test]
    fn an_unescapable_name_is_an_error() {
        assert_eq!(
            method_name(&field("Self", 9000, DataType::String)).unwrap_err(),
            Error::UnrepresentableName {
                field: "Self".to_owned(),
            }
        );
    }

    #[test]
    fn a_suffix_makes_an_unescapable_name_legal() {
        let name = method_name(&field("Self", 9000, DataType::Other("DATA".to_owned())));
        assert_eq!(name.unwrap(), "self_raw");
    }
}
