mod enums;
mod error;
mod groups;
mod layout;
mod messages;
mod names;
mod naming;
mod views;

use refix_dictionary::{Dictionary, dictionary};

use crate::Generated;
use crate::envelope::Envelope;
use crate::groups::is_generated;
use enums::emit_enum;
pub use error::Error;
use groups::{emit_group_class, shared_groups};
use messages::emit_message;
use names::Names;
use views::emit_view;

pub fn generate(dictionary: &Dictionary, source: &str) -> Result<Generated, Error> {
    let mut warnings = Vec::new();
    let names = Names::new(dictionary, &mut warnings)?;
    let envelope = Envelope::of(dictionary);

    // The layout is the emitter's own, so formatters leave it alone.
    let header = format!("# @generated by refix codegen from {source}. Do not edit.\n# fmt: off\n");
    let enums: Vec<String> = dictionary
        .fields()
        .iter()
        .filter(|field| !field.values.is_empty())
        .map(|field| emit_enum(field, &names))
        .collect();
    let groups: Vec<String> = shared_groups(dictionary, &mut warnings)
        .into_iter()
        .map(|group| emit_group_class(group, 0, &names))
        .collect();
    let views: Vec<String> = envelope
        .sections
        .iter()
        .map(|section| emit_view(*section, dictionary, &envelope, &names))
        .collect();
    let messages: Vec<String> = dictionary
        .messages()
        .map(|message| emit_message(message, &envelope, &names))
        .collect();
    let imports = emit_imports(dictionary, &envelope, !enums.is_empty());
    let sections = imports
        .into_iter()
        .chain(enums)
        .chain(groups)
        .chain(views)
        .chain(messages)
        .collect::<Vec<String>>()
        .join("\n\n");
    let code = format!("{header}\n{sections}");

    Ok(Generated { code, warnings })
}

/// The import block, naming only what the module uses.
fn emit_imports(dictionary: &Dictionary, envelope: &Envelope, has_enums: bool) -> Option<String> {
    let has_classes = dictionary.messages().next().is_some() || !envelope.sections.is_empty();
    let has_properties = !envelope.sections.is_empty()
        || dictionary
            .messages()
            .any(|message| message.members().next().is_some());
    let has_groups = !envelope.with_groups.is_empty()
        || dictionary.messages().any(|message| {
            message
                .members()
                .any(|member| matches!(member, dictionary::Member::Group(_)))
        });
    let reads_enums = reads_enums(dictionary.header().chain(dictionary.trailer()))
        || dictionary
            .messages()
            .any(|message| reads_enums(message.members()));

    let mut blocks = Vec::new();
    if has_classes {
        blocks.push(vec!["from __future__ import annotations\n"]);
    }
    let mut standard = Vec::new();
    if has_enums {
        standard.push("import enum\n");
    }
    if has_properties {
        standard.push("from functools import cached_property\n");
    }
    if has_classes {
        standard.push("from typing import ClassVar\n");
    }
    blocks.push(standard);
    let mut refix = Vec::new();
    // `Scope` stays qualified: FIX44's `Scope(546)` generates an enum of that name.
    if has_groups {
        refix.push("import refix\n");
        refix.push("from refix import GroupTable, KnownTags, RawMessage\n");
    } else if has_classes {
        refix.push("from refix import KnownTags, RawMessage\n");
    }
    if reads_enums {
        refix.push("from refix.enums import Unrecognized, from_value\n");
    }
    blocks.push(refix);
    let blocks: Vec<String> = blocks
        .into_iter()
        .filter(|block| !block.is_empty())
        .map(|block| block.concat())
        .collect();
    (!blocks.is_empty()).then(|| blocks.join("\n"))
}

/// Whether a property generated for `members` reads an enum, inside group
/// instances too.
fn reads_enums<'a>(mut members: impl Iterator<Item = dictionary::Member<'a>>) -> bool {
    members.any(|member| match member {
        dictionary::Member::Field { field, .. } => !field.values.is_empty(),
        dictionary::Member::Group(group) => is_generated(group) && reads_enums(group.members()),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Warning;
    use refix_dictionary::{
        Category, Component, ComponentRef, DataType, EnumValue, Field, FieldRef, Group, Member,
        MemberContext, Message, Protocol, Spec, Tag, Version,
    };

    fn field(name: &str, tag: u32, data_type: DataType, values: &[(&str, &str)]) -> Field {
        Field {
            name: name.to_owned(),
            tag: Tag(tag),
            data_type,
            values: values
                .iter()
                .map(|(value, description)| EnumValue {
                    value: (*value).to_owned(),
                    description: (*description).to_owned(),
                })
                .collect(),
        }
    }

    fn field_ref(tag: u32) -> Member {
        Member::Field(FieldRef {
            tag: Tag(tag),
            is_required: false,
        })
    }

    fn message(name: &str, msg_type: &str, members: Vec<Member>) -> Message {
        Message {
            name: name.to_owned(),
            msg_type: msg_type.to_owned(),
            members,
            category: Category::App,
        }
    }

    fn generated(
        messages: Vec<Message>,
        fields: Vec<Field>,
        components: Vec<Component>,
    ) -> Generated {
        let spec = Spec {
            version: Version {
                protocol: Protocol::Fix,
                major: 4,
                minor: 4,
                service_pack: 0,
            },
            header: vec![],
            trailer: vec![],
            messages,
            fields,
            components,
        };
        generate(&spec.resolve().unwrap(), "toy.xml").unwrap()
    }

    #[test]
    fn generates_a_complete_module() {
        let generated = generated(
            vec![message(
                "NewOrderSingle",
                "D",
                [11, 38, 44, 40, 452, 18].map(field_ref).to_vec(),
            )],
            vec![
                field("ClOrdID", 11, DataType::String, &[]),
                field("OrderQty", 38, DataType::Int, &[]),
                field("Price", 44, DataType::Other("PRICE".to_owned()), &[]),
                field(
                    "OrdType",
                    40,
                    DataType::Char,
                    &[("1", "MARKET"), ("2", "LIMIT")],
                ),
                field("PartyRole", 452, DataType::Int, &[("3", "CLIENT_ID")]),
                field(
                    "ExecInst",
                    18,
                    DataType::MultipleStringValue,
                    &[("1", "NOT_HELD")],
                ),
            ],
            vec![],
        );

        let expected = r#"# @generated by refix codegen from toy.xml. Do not edit.
# fmt: off

from __future__ import annotations

import enum
from functools import cached_property
from typing import ClassVar

from refix import KnownTags, RawMessage
from refix.enums import Unrecognized, from_value


class OrdType(enum.StrEnum):
    MARKET = "1"
    LIMIT = "2"


class PartyRole(enum.IntEnum):
    CLIENT_ID = 3


class ExecInst(enum.StrEnum):
    NOT_HELD = "1"


class NewOrderSingle:
    MSG_TYPE: ClassVar[bytes] = b"D"

    KNOWN_TAGS: ClassVar[KnownTags] = KnownTags((11, 18, 38, 40, 44, 452))

    def __init__(self, raw: RawMessage) -> None:
        self._raw = raw

    @property
    def raw(self) -> RawMessage:
        return self._raw

    @cached_property
    def cl_ord_id(self) -> str | None:
        return self._raw.get_str(11)

    @cached_property
    def order_qty(self) -> int | None:
        return self._raw.get_int(38)

    @cached_property
    def price_raw(self) -> bytes | None:
        return self._raw.get(44)

    @cached_property
    def ord_type(self) -> OrdType | Unrecognized[str] | None:
        value = self._raw.get_str(40)
        return None if value is None else from_value(OrdType, value)

    @cached_property
    def party_role(self) -> PartyRole | Unrecognized[int] | None:
        value = self._raw.get_int(452)
        return None if value is None else from_value(PartyRole, value)

    @cached_property
    def exec_inst(self) -> tuple[ExecInst | Unrecognized[str], ...] | None:
        values = self._raw.get_multiple_values(18)
        return None if values is None else tuple(from_value(ExecInst, value) for value in values)
"#;
        assert_eq!(generated.code, expected);
        assert!(generated.warnings.is_empty());
    }

    #[test]
    fn imports_only_what_the_module_uses() {
        let with_a_field = generated(
            vec![message("Heartbeat", "0", vec![field_ref(112)])],
            vec![field("TestReqID", 112, DataType::String, &[])],
            vec![],
        );
        let without_fields = generated(vec![message("Logout", "5", vec![])], vec![], vec![]);

        let imports = |code: &str| code.split("\n\n\n").next().unwrap().to_owned();
        assert_eq!(
            imports(&with_a_field.code),
            "# @generated by refix codegen from toy.xml. Do not edit.\n# fmt: off\n\nfrom __future__ import annotations\n\nfrom functools import cached_property\nfrom typing import ClassVar\n\nfrom refix import KnownTags, RawMessage"
        );
        assert_eq!(
            imports(&without_fields.code),
            "# @generated by refix codegen from toy.xml. Do not edit.\n# fmt: off\n\nfrom __future__ import annotations\n\nfrom typing import ClassVar\n\nfrom refix import KnownTags, RawMessage"
        );
    }

    fn group(count_tag: u32, members: Vec<Member>) -> Member {
        Member::Group(Group {
            count_tag: Tag(count_tag),
            is_required: false,
            members,
        })
    }

    fn component_ref(name: &str) -> Member {
        Member::Component(ComponentRef {
            name: name.to_owned(),
            is_required: false,
        })
    }

    fn component(name: &str, members: Vec<Member>) -> Component {
        Component {
            name: name.to_owned(),
            members,
        }
    }

    fn party_fields() -> Vec<Field> {
        vec![
            field("NoPartyIDs", 453, DataType::NumInGroup, &[]),
            field("PartyID", 448, DataType::String, &[]),
            field("NoPartySubIDs", 802, DataType::NumInGroup, &[]),
            field("PartySubID", 523, DataType::String, &[]),
        ]
    }

    /// `Parties` and its nested `PtysSubGrp`, as FIX44 declares them.
    fn party_components() -> Vec<Component> {
        vec![
            component(
                "Parties",
                vec![group(
                    453,
                    vec![field_ref(448), component_ref("PtysSubGrp")],
                )],
            ),
            component("PtysSubGrp", vec![group(802, vec![field_ref(523)])]),
        ]
    }

    #[test]
    fn generates_a_class_per_group_innermost_first() {
        let generated = generated(
            vec![message(
                "NewOrderSingle",
                "D",
                vec![component_ref("Parties")],
            )],
            party_fields(),
            party_components(),
        );

        let expected = r#"# @generated by refix codegen from toy.xml. Do not edit.
# fmt: off

from __future__ import annotations

from functools import cached_property
from typing import ClassVar

import refix
from refix import GroupTable, KnownTags, RawMessage


class PtysSubGrp:
    TABLE: ClassVar[GroupTable] = GroupTable(802, 523, (523,), ())

    KNOWN_TAGS: ClassVar[KnownTags] = KnownTags((523,))

    class Instance:
        def __init__(self, scope: refix.Scope) -> None:
            self._scope = scope

        @property
        def raw(self) -> refix.Scope:
            return self._scope

        @cached_property
        def party_sub_id(self) -> str | None:
            return self._scope.get_str(523)


class Parties:
    TABLE: ClassVar[GroupTable] = GroupTable(453, 448, (448, 802), (PtysSubGrp.TABLE,))

    KNOWN_TAGS: ClassVar[KnownTags] = KnownTags((448, 523, 802))

    class Instance:
        def __init__(self, scope: refix.Scope) -> None:
            self._scope = scope

        @property
        def raw(self) -> refix.Scope:
            return self._scope

        @cached_property
        def party_id(self) -> str | None:
            return self._scope.get_str(448)

        @cached_property
        def ptys_sub_grp(self) -> tuple[PtysSubGrp.Instance, ...]:
            scopes = self._scope.get_group(PtysSubGrp.TABLE, Parties.KNOWN_TAGS)
            return () if scopes is None else tuple(PtysSubGrp.Instance(scope) for scope in scopes)


class NewOrderSingle:
    MSG_TYPE: ClassVar[bytes] = b"D"

    KNOWN_TAGS: ClassVar[KnownTags] = KnownTags((448, 453, 523, 802))

    def __init__(self, raw: RawMessage) -> None:
        self._raw = raw

    @property
    def raw(self) -> RawMessage:
        return self._raw

    @cached_property
    def parties(self) -> tuple[Parties.Instance, ...]:
        scopes = self._raw.get_group(Parties.TABLE, NewOrderSingle.KNOWN_TAGS)
        return () if scopes is None else tuple(Parties.Instance(scope) for scope in scopes)
"#;
        assert_eq!(generated.code, expected);
        assert!(generated.warnings.is_empty());
    }

    #[test]
    fn a_shared_group_is_generated_once() {
        let generated = generated(
            vec![
                message("NewOrderSingle", "D", vec![component_ref("Parties")]),
                message("OrderCancelRequest", "F", vec![component_ref("Parties")]),
            ],
            party_fields(),
            party_components(),
        );

        assert_eq!(generated.code.matches("class Parties:").count(), 1);
        assert_eq!(generated.code.matches("def parties(self)").count(), 2);
    }

    #[test]
    fn a_message_group_nests_in_its_class() {
        let generated = generated(
            vec![message(
                "Logon",
                "A",
                vec![group(384, vec![field_ref(372)])],
            )],
            vec![
                field("NoMsgTypes", 384, DataType::NumInGroup, &[]),
                field("RefMsgType", 372, DataType::String, &[]),
            ],
            vec![],
        );

        assert!(generated.code.contains(
            "class Logon:\n    MSG_TYPE: ClassVar[bytes] = b\"A\"\n\n    KNOWN_TAGS: ClassVar[KnownTags] = KnownTags((372, 384))\n\n    class MsgTypes:\n        TABLE: ClassVar[GroupTable] = GroupTable(384, 372, (372,), ())\n"
        ));
        assert!(
            generated
                .code
                .contains("scopes = self._raw.get_group(Logon.MsgTypes.TABLE, Logon.KNOWN_TAGS)")
        );
    }

    #[test]
    fn an_enum_named_like_a_message_is_renamed_with_a_warning() {
        let generated = generated(
            vec![message("SecurityStatus", "f", vec![field_ref(965)])],
            vec![field(
                "SecurityStatus",
                965,
                DataType::String,
                &[("1", "ACTIVE")],
            )],
            vec![],
        );

        assert!(
            generated
                .code
                .contains("class SecurityStatusEnum(enum.StrEnum):")
        );
        assert!(generated.code.contains("class SecurityStatus:"));
        assert!(
            generated
                .code
                .contains("from_value(SecurityStatusEnum, value)")
        );
        assert!(matches!(
            generated.warnings.as_slice(),
            [Warning::Renamed { .. }]
        ));
    }

    #[test]
    fn a_group_in_a_group_instance_is_skipped_with_a_warning() {
        let generated = generated(
            vec![message(
                "NewOrderSingle",
                "D",
                vec![component_ref("Parties")],
            )],
            party_fields(),
            vec![component(
                "Parties",
                vec![group(
                    453,
                    vec![field_ref(448), group(802, vec![field_ref(523)])],
                )],
            )],
        );

        assert!(!generated.code.contains("party_sub_id"));
        assert!(
            generated
                .code
                .contains("        (GroupTable(802, 523, (523,), ()),),\n")
        );
        assert_eq!(
            generated.warnings,
            vec![Warning::UnsupportedGroup {
                context: MemberContext::Component("Parties".to_owned())
                    .group("NoPartyIDs")
                    .group("NoPartySubIDs"),
            }]
        );
    }
}
