mod enums;
mod error;
mod messages;
mod naming;

use refix_dictionary::{Dictionary, dictionary};

use crate::{Generated, Warning};
use enums::emit_enum;
pub use error::Error;
use messages::emit_message;

pub fn generate(dictionary: &Dictionary, source: &str) -> Result<Generated, Error> {
    // The layout is the emitter's own, so formatters leave it alone.
    let header = format!("# @generated by refix codegen from {source}. Do not edit.\n# fmt: off\n");
    let enums: Vec<String> = dictionary
        .fields()
        .iter()
        .filter(|field| !field.values.is_empty())
        .map(emit_enum)
        .collect::<Result<Vec<_>, _>>()?;
    let messages: Vec<String> = dictionary.messages().map(emit_message).collect();
    let imports = emit_imports(dictionary, !enums.is_empty());
    let sections = imports
        .into_iter()
        .chain(enums)
        .chain(messages)
        .collect::<Vec<String>>()
        .join("\n\n");
    let code = format!("{header}\n{sections}");

    Ok(Generated {
        code,
        warnings: unsupported_groups(dictionary),
    })
}

/// The import block, naming only what the module uses.
fn emit_imports(dictionary: &Dictionary, has_enums: bool) -> Option<String> {
    let has_messages = dictionary.messages().next().is_some();
    let fields = || {
        dictionary.messages().flat_map(|message| {
            message
                .members()
                .filter_map(|member| match member {
                    dictionary::Member::Field { field, .. } => Some(field),
                    dictionary::Member::Group(_) => None,
                })
                .collect::<Vec<_>>()
        })
    };
    let has_properties = fields().next().is_some();
    let reads_enums = fields().any(|field| !field.values.is_empty());

    let mut standard = Vec::new();
    if has_enums {
        standard.push("import enum\n");
    }
    if has_properties {
        standard.push("from functools import cached_property\n");
    }
    if has_messages {
        standard.push("from typing import ClassVar\n");
    }
    let mut refix = Vec::new();
    if has_messages {
        refix.push("from refix import RawMessage\n");
    }
    if reads_enums {
        refix.push("from refix.enums import Unrecognized, from_value\n");
    }
    let blocks: Vec<String> = [standard, refix]
        .into_iter()
        .filter(|block| !block.is_empty())
        .map(|block| block.concat())
        .collect();
    (!blocks.is_empty()).then(|| blocks.join("\n"))
}

/// One warning per group declaration a message reaches, since the Python
/// backend does not generate groups yet.
fn unsupported_groups(dictionary: &Dictionary) -> Vec<Warning> {
    let mut warnings = Vec::new();
    for message in dictionary.messages() {
        for member in message.members() {
            if let dictionary::Member::Group(group) = member {
                let warning = Warning::UnsupportedGroup {
                    context: group.declared_in().group(&group.count_field().name),
                };
                if !warnings.contains(&warning) {
                    warnings.push(warning);
                }
            }
        }
    }
    warnings
}

#[cfg(test)]
mod tests {
    use super::*;
    use refix_dictionary::{
        Category, Component, ComponentRef, DataType, EnumValue, Field, FieldRef, Group, Member,
        MemberContext, Message, Protocol, Spec, Tag, Version,
    };

    fn field(name: &str, tag: u32, data_type: DataType, values: &[(&str, &str)]) -> Field {
        Field {
            name: name.to_owned(),
            tag: Tag(tag),
            data_type,
            values: values
                .iter()
                .map(|(value, description)| EnumValue {
                    value: (*value).to_owned(),
                    description: (*description).to_owned(),
                })
                .collect(),
        }
    }

    fn field_ref(tag: u32) -> Member {
        Member::Field(FieldRef {
            tag: Tag(tag),
            is_required: false,
        })
    }

    fn message(name: &str, msg_type: &str, members: Vec<Member>) -> Message {
        Message {
            name: name.to_owned(),
            msg_type: msg_type.to_owned(),
            members,
            category: Category::App,
        }
    }

    fn generated(
        messages: Vec<Message>,
        fields: Vec<Field>,
        components: Vec<Component>,
    ) -> Generated {
        let spec = Spec {
            version: Version {
                protocol: Protocol::Fix,
                major: 4,
                minor: 4,
                service_pack: 0,
            },
            messages,
            fields,
            components,
        };
        generate(&spec.resolve().unwrap(), "toy.xml").unwrap()
    }

    #[test]
    fn generates_a_complete_module() {
        let generated = generated(
            vec![message(
                "NewOrderSingle",
                "D",
                [11, 38, 44, 40, 452, 18].map(field_ref).to_vec(),
            )],
            vec![
                field("ClOrdID", 11, DataType::String, &[]),
                field("OrderQty", 38, DataType::Int, &[]),
                field("Price", 44, DataType::Other("PRICE".to_owned()), &[]),
                field(
                    "OrdType",
                    40,
                    DataType::Char,
                    &[("1", "MARKET"), ("2", "LIMIT")],
                ),
                field("PartyRole", 452, DataType::Int, &[("3", "CLIENT_ID")]),
                field(
                    "ExecInst",
                    18,
                    DataType::MultipleStringValue,
                    &[("1", "NOT_HELD")],
                ),
            ],
            vec![],
        );

        let expected = r#"# @generated by refix codegen from toy.xml. Do not edit.
# fmt: off

import enum
from functools import cached_property
from typing import ClassVar

from refix import RawMessage
from refix.enums import Unrecognized, from_value


class OrdType(enum.StrEnum):
    MARKET = "1"
    LIMIT = "2"


class PartyRole(enum.IntEnum):
    CLIENT_ID = 3


class ExecInst(enum.StrEnum):
    NOT_HELD = "1"


class NewOrderSingle:
    MSG_TYPE: ClassVar[bytes] = b"D"

    def __init__(self, raw: RawMessage) -> None:
        self._raw = raw

    @property
    def raw(self) -> RawMessage:
        return self._raw

    @cached_property
    def cl_ord_id(self) -> str | None:
        return self._raw.get_str(11)

    @cached_property
    def order_qty(self) -> int | None:
        return self._raw.get_int(38)

    @cached_property
    def price_raw(self) -> bytes | None:
        return self._raw.get(44)

    @cached_property
    def ord_type(self) -> OrdType | Unrecognized[str] | None:
        value = self._raw.get_str(40)
        return None if value is None else from_value(OrdType, value)

    @cached_property
    def party_role(self) -> PartyRole | Unrecognized[int] | None:
        value = self._raw.get_int(452)
        return None if value is None else from_value(PartyRole, value)

    @cached_property
    def exec_inst(self) -> tuple[ExecInst | Unrecognized[str], ...] | None:
        values = self._raw.get_multiple_values(18)
        return None if values is None else tuple(from_value(ExecInst, value) for value in values)
"#;
        assert_eq!(generated.code, expected);
        assert!(generated.warnings.is_empty());
    }

    #[test]
    fn imports_only_what_the_module_uses() {
        let with_a_field = generated(
            vec![message("Heartbeat", "0", vec![field_ref(112)])],
            vec![field("TestReqID", 112, DataType::String, &[])],
            vec![],
        );
        let without_fields = generated(vec![message("Logout", "5", vec![])], vec![], vec![]);

        let imports = |code: &str| code.split("\n\n\n").next().unwrap().to_owned();
        assert_eq!(
            imports(&with_a_field.code),
            "# @generated by refix codegen from toy.xml. Do not edit.\n# fmt: off\n\nfrom functools import cached_property\nfrom typing import ClassVar\n\nfrom refix import RawMessage"
        );
        assert_eq!(
            imports(&without_fields.code),
            "# @generated by refix codegen from toy.xml. Do not edit.\n# fmt: off\n\nfrom typing import ClassVar\n\nfrom refix import RawMessage"
        );
    }

    #[test]
    fn a_group_is_skipped_with_one_warning_per_declaration() {
        let parties = Component {
            name: "Parties".to_owned(),
            members: vec![Member::Group(Group {
                count_tag: Tag(453),
                is_required: false,
                members: vec![field_ref(448)],
            })],
        };
        let uses_parties = |name: &str, msg_type: &str| {
            message(
                name,
                msg_type,
                vec![
                    field_ref(11),
                    Member::Component(ComponentRef {
                        name: "Parties".to_owned(),
                        is_required: false,
                    }),
                ],
            )
        };

        let generated = generated(
            vec![
                uses_parties("NewOrderSingle", "D"),
                uses_parties("OrderCancelRequest", "F"),
            ],
            vec![
                field("ClOrdID", 11, DataType::String, &[]),
                field("NoPartyIDs", 453, DataType::NumInGroup, &[]),
                field("PartyID", 448, DataType::String, &[]),
            ],
            vec![parties],
        );

        assert!(!generated.code.contains("party_id"));
        assert_eq!(generated.code.matches("def cl_ord_id").count(), 2);
        assert_eq!(
            generated.warnings,
            vec![Warning::UnsupportedGroup {
                context: MemberContext::Component("Parties".to_owned()).group("NoPartyIDs"),
            }]
        );
    }
}
