mod enums;
mod error;
mod groups;
mod layout;
mod messages;
mod names;
mod naming;
mod views;

use refix_dictionary::{Dictionary, dictionary};

use crate::Generated;
use crate::envelope::Envelope;
use crate::groups::is_generated;
use enums::emit_enum;
pub use error::Error;
use groups::{emit_group_module, shared_groups};
use messages::emit_message;
use names::Names;
use views::emit_view;

pub fn generate(dictionary: &Dictionary, source: &str) -> Result<Generated, Error> {
    let mut warnings = Vec::new();
    let names = Names::new(dictionary, &mut warnings)?;
    let envelope = Envelope::of(dictionary);

    // The layout is the emitter's own, so rustfmt leaves it alone. That keeps
    // the output byte-stable across rustfmt versions. A message may declare a
    // group named like itself, a module in a module of the same name, which
    // clippy flags in code its users cannot change.
    let header = format!(
        "// @generated by refix codegen from {source}. Do not edit.\n#![cfg_attr(rustfmt, rustfmt::skip)]\n#![allow(clippy::module_inception)]\n"
    );
    let enums: Vec<String> = dictionary
        .fields()
        .iter()
        .filter(|field| !field.values.is_empty())
        .map(|field| emit_enum(field, &names))
        .collect();
    let groups: Vec<String> = shared_groups(dictionary, &mut warnings)
        .into_iter()
        .map(|group| emit_group_module(group, &names))
        .collect();
    let views: Vec<String> = envelope
        .sections
        .iter()
        .map(|section| emit_view(*section, dictionary, &envelope, &names))
        .collect();
    let messages: Vec<String> = dictionary
        .messages()
        .map(|message| emit_message(message, &envelope, &names))
        .collect();
    let sections = enums
        .into_iter()
        .chain(groups)
        .chain(views)
        .chain(messages)
        .collect::<Vec<String>>()
        .join("\n");
    let has_groups = !envelope.with_groups.is_empty()
        || dictionary.messages().any(|message| {
            message
                .members()
                .any(|member| matches!(member, dictionary::Member::Group(_)))
        });
    let mut imports = vec!["InvalidValue", "KnownTags", "RawMessage", "Tag"];
    if has_groups {
        imports.extend(["GroupTable", "Instances"]);
    }
    if reads_multiple_values(dictionary.header().chain(dictionary.trailer()))
        || dictionary
            .messages()
            .any(|message| reads_multiple_values(message.members()))
    {
        imports.push("MultipleValues");
    }
    imports.sort_unstable();
    let imports = format!("use refix_message::{{{}}};", imports.join(", "));
    let code = format!("{header}\n{imports}\n\n{sections}");

    Ok(Generated { code, warnings })
}

/// Whether an accessor generated for `members` reads a multiple-value field.
fn reads_multiple_values<'a>(mut members: impl Iterator<Item = dictionary::Member<'a>>) -> bool {
    members.any(|member| match member {
        dictionary::Member::Field { field, .. } => {
            !field.values.is_empty() && field.data_type.is_multiple_value()
        }
        dictionary::Member::Group(group) => {
            is_generated(group) && reads_multiple_values(group.members())
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Warning;
    use refix_dictionary::{
        Category, DataType, EnumValue, Field, FieldRef, Group, Member, MemberContext, Message,
        Protocol, Spec, Tag, Version,
    };

    fn field(name: &str, tag: u32, data_type: DataType) -> Field {
        Field {
            name: name.to_owned(),
            tag: Tag(tag),
            data_type,
            values: vec![],
        }
    }

    fn spec_of(messages: Vec<Message>, fields: Vec<Field>) -> Spec {
        Spec {
            version: Version {
                protocol: Protocol::Fix,
                major: 4,
                minor: 4,
                service_pack: 0,
            },
            header: vec![],
            trailer: vec![],
            messages,
            components: vec![],
            fields,
        }
    }

    #[test]
    fn generates_a_complete_module() {
        let mut ord_type = field("OrdType", 40, DataType::Char);
        ord_type.values = vec![
            EnumValue {
                value: "1".to_owned(),
                description: "MARKET".to_owned(),
            },
            EnumValue {
                value: "2".to_owned(),
                description: "LIMIT".to_owned(),
            },
        ];
        let spec = spec_of(
            vec![Message {
                name: "NewOrderSingle".to_owned(),
                msg_type: "D".to_owned(),
                members: vec![
                    Member::Field(FieldRef {
                        tag: Tag(11),
                        is_required: true,
                    }),
                    Member::Field(FieldRef {
                        tag: Tag(38),
                        is_required: false,
                    }),
                    Member::Field(FieldRef {
                        tag: Tag(44),
                        is_required: false,
                    }),
                    Member::Field(FieldRef {
                        tag: Tag(40),
                        is_required: false,
                    }),
                ],
                category: Category::App,
            }],
            vec![
                field("ClOrdID", 11, DataType::String),
                field("OrderQty", 38, DataType::Int),
                field("Price", 44, DataType::Other("PRICE".to_owned())),
                ord_type,
            ],
        );

        let expected = r#"// @generated by refix codegen from toy.xml. Do not edit.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(clippy::module_inception)]

use refix_message::{InvalidValue, KnownTags, RawMessage, Tag};

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum OrdType<'a> {
    Market,
    Limit,
    Unrecognized(&'a str),
}

impl<'a> OrdType<'a> {
    pub fn from_value(value: &'a str) -> Self {
        match value {
            "1" => Self::Market,
            "2" => Self::Limit,
            unrecognized => Self::Unrecognized(unrecognized),
        }
    }

    pub fn value(self) -> &'a str {
        match self {
            Self::Market => "1",
            Self::Limit => "2",
            Self::Unrecognized(value) => value,
        }
    }
}

impl<'a> From<&'a str> for OrdType<'a> {
    fn from(value: &'a str) -> Self {
        Self::from_value(value)
    }
}

pub struct NewOrderSingle(RawMessage);

impl NewOrderSingle {
    pub const MSG_TYPE: &[u8] = b"D";

    pub const KNOWN_TAGS: KnownTags<'static> = KnownTags::new(&[
        Tag(11), Tag(38), Tag(40), Tag(44),
    ]);

    pub fn from_raw(raw: RawMessage) -> Self {
        Self(raw)
    }

    pub fn raw(&self) -> &RawMessage {
        &self.0
    }

    pub fn cl_ord_id(&self) -> Result<Option<&str>, InvalidValue> {
        self.0.get_str(Tag(11))
    }

    pub fn order_qty(&self) -> Result<Option<i64>, InvalidValue> {
        self.0.get_int(Tag(38))
    }

    pub fn price_raw(&self) -> Option<&[u8]> {
        self.0.get(Tag(44))
    }

    pub fn ord_type(&self) -> Result<Option<OrdType<'_>>, InvalidValue> {
        Ok(self.0.get_str(Tag(40))?.map(OrdType::from_value))
    }
}
"#;

        assert_eq!(
            generate(&spec.resolve().unwrap(), "toy.xml").unwrap().code,
            expected
        );
    }

    #[test]
    fn imports_multiple_values_only_when_read() {
        let mut exec_inst = field("ExecInst", 18, DataType::MultipleStringValue);
        exec_inst.values = vec![EnumValue {
            value: "1".to_owned(),
            description: "NOT_HELD".to_owned(),
        }];
        let order = |members| Message {
            name: "NewOrderSingle".to_owned(),
            msg_type: "D".to_owned(),
            members,
            category: Category::App,
        };
        let reads = spec_of(
            vec![order(vec![Member::Field(FieldRef {
                tag: Tag(18),
                is_required: false,
            })])],
            vec![exec_inst.clone()],
        );
        let unused = spec_of(vec![order(vec![])], vec![exec_inst]);

        let imports = |spec: Spec| {
            let code = generate(&spec.resolve().unwrap(), "toy.xml").unwrap().code;
            code.lines()
                .find(|line| line.starts_with("use "))
                .unwrap()
                .to_owned()
        };

        assert_eq!(
            imports(reads),
            "use refix_message::{InvalidValue, KnownTags, MultipleValues, RawMessage, Tag};"
        );
        assert_eq!(
            imports(unused),
            "use refix_message::{InvalidValue, KnownTags, RawMessage, Tag};"
        );
    }

    #[test]
    fn an_enum_named_like_a_message_is_renamed_with_a_warning() {
        let mut security_status = field("SecurityStatus", 965, DataType::String);
        security_status.values = vec![EnumValue {
            value: "1".to_owned(),
            description: "ACTIVE".to_owned(),
        }];
        let spec = spec_of(
            vec![Message {
                name: "SecurityStatus".to_owned(),
                msg_type: "f".to_owned(),
                members: vec![Member::Field(FieldRef {
                    tag: Tag(965),
                    is_required: false,
                })],
                category: Category::App,
            }],
            vec![security_status],
        );

        let generated = generate(&spec.resolve().unwrap(), "toy.xml").unwrap();

        assert!(generated.code.contains("pub enum SecurityStatusEnum<'a> {"));
        assert!(
            generated
                .code
                .contains("pub struct SecurityStatus(RawMessage);")
        );
        assert!(
            generated
                .code
                .contains("Result<Option<SecurityStatusEnum<'_>>, InvalidValue>")
        );
        assert!(matches!(
            generated.warnings.as_slice(),
            [Warning::Renamed { .. }]
        ));
    }

    #[test]
    fn emits_messages_in_spec_order() {
        let spec = spec_of(
            vec![
                Message {
                    name: "Heartbeat".to_owned(),
                    msg_type: "0".to_owned(),
                    members: vec![],
                    category: Category::Admin,
                },
                Message {
                    name: "TestRequest".to_owned(),
                    msg_type: "1".to_owned(),
                    members: vec![],
                    category: Category::Admin,
                },
            ],
            vec![],
        );

        let generated = generate(&spec.resolve().unwrap(), "toy.xml").unwrap();

        let heartbeat = generated.code.find("pub struct Heartbeat").unwrap();
        let test_request = generated.code.find("pub struct TestRequest").unwrap();
        assert!(heartbeat < test_request);
    }

    mod groups {
        use super::*;
        use refix_dictionary::{Component, ComponentRef};

        fn field_ref(tag: u32) -> Member {
            Member::Field(FieldRef {
                tag: Tag(tag),
                is_required: false,
            })
        }

        fn component_ref(name: &str) -> Member {
            Member::Component(ComponentRef {
                name: name.to_owned(),
                is_required: false,
            })
        }

        fn group(count_tag: u32, members: Vec<Member>) -> Member {
            Member::Group(Group {
                count_tag: Tag(count_tag),
                is_required: false,
                members,
            })
        }

        fn message(name: &str, msg_type: &str, members: Vec<Member>) -> Message {
            Message {
                name: name.to_owned(),
                msg_type: msg_type.to_owned(),
                members,
                category: Category::App,
            }
        }

        /// A spec with `Parties` and its nested `PtysSubGrp`, as FIX44
        /// declares them, used by `messages`.
        fn parties_spec(messages: Vec<Message>) -> Spec {
            let mut spec = spec_of(
                messages,
                vec![
                    field("NoPartyIDs", 453, DataType::NumInGroup),
                    field("PartyID", 448, DataType::String),
                    field("NoPartySubIDs", 802, DataType::NumInGroup),
                    field("PartySubID", 523, DataType::String),
                ],
            );
            spec.components = vec![
                Component {
                    name: "Parties".to_owned(),
                    members: vec![group(
                        453,
                        vec![field_ref(448), component_ref("PtysSubGrp")],
                    )],
                },
                Component {
                    name: "PtysSubGrp".to_owned(),
                    members: vec![group(802, vec![field_ref(523)])],
                },
            ];
            spec
        }

        fn generated(spec: Spec) -> Generated {
            generate(&spec.resolve().unwrap(), "toy.xml").unwrap()
        }

        #[test]
        fn generates_a_module_per_group() {
            let spec = parties_spec(vec![message(
                "NewOrderSingle",
                "D",
                vec![component_ref("Parties")],
            )]);

            let expected = r#"// @generated by refix codegen from toy.xml. Do not edit.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(clippy::module_inception)]

use refix_message::{GroupTable, Instances, InvalidValue, KnownTags, RawMessage, Tag};

pub mod parties {
    use super::*;

    pub const TABLE: GroupTable<'static> = GroupTable::new(
        Tag(453),
        Tag(448),
        &[Tag(448), Tag(802)],
        &[ptys_sub_grp::TABLE],
    );

    pub const KNOWN_TAGS: KnownTags<'static> = KnownTags::new(&[Tag(448), Tag(523), Tag(802)]);

    #[derive(Clone, Copy, Debug)]
    pub struct Instance<'a>(refix_message::Scope<'a>);

    impl<'a> From<refix_message::Scope<'a>> for Instance<'a> {
        fn from(scope: refix_message::Scope<'a>) -> Self {
            Self(scope)
        }
    }

    impl<'a> Instance<'a> {
        pub fn raw(&self) -> refix_message::Scope<'a> {
            self.0
        }

        pub fn party_id(&self) -> Result<Option<&'a str>, InvalidValue> {
            self.0.get_str(Tag(448))
        }

        pub fn ptys_sub_grp(&self) -> Result<Instances<'a, ptys_sub_grp::Instance<'a>>, InvalidValue> {
            self.0.get_group(&ptys_sub_grp::TABLE, &KNOWN_TAGS).map(Instances::from)
        }
    }
}

pub mod ptys_sub_grp {
    use super::*;

    pub const TABLE: GroupTable<'static> = GroupTable::new(Tag(802), Tag(523), &[Tag(523)], &[]);

    pub const KNOWN_TAGS: KnownTags<'static> = KnownTags::new(&[Tag(523)]);

    #[derive(Clone, Copy, Debug)]
    pub struct Instance<'a>(refix_message::Scope<'a>);

    impl<'a> From<refix_message::Scope<'a>> for Instance<'a> {
        fn from(scope: refix_message::Scope<'a>) -> Self {
            Self(scope)
        }
    }

    impl<'a> Instance<'a> {
        pub fn raw(&self) -> refix_message::Scope<'a> {
            self.0
        }

        pub fn party_sub_id(&self) -> Result<Option<&'a str>, InvalidValue> {
            self.0.get_str(Tag(523))
        }
    }
}

pub struct NewOrderSingle(RawMessage);

impl NewOrderSingle {
    pub const MSG_TYPE: &[u8] = b"D";

    pub const KNOWN_TAGS: KnownTags<'static> = KnownTags::new(&[
        Tag(448), Tag(453), Tag(523), Tag(802),
    ]);

    pub fn from_raw(raw: RawMessage) -> Self {
        Self(raw)
    }

    pub fn raw(&self) -> &RawMessage {
        &self.0
    }

    pub fn parties(&self) -> Result<Instances<'_, parties::Instance<'_>>, InvalidValue> {
        self.0.get_group(&parties::TABLE, &Self::KNOWN_TAGS).map(Instances::from)
    }
}
"#;

            let generated = generated(spec);
            assert_eq!(generated.code, expected);
            assert!(generated.warnings.is_empty());
        }

        #[test]
        fn a_shared_group_is_emitted_once() {
            let spec = parties_spec(vec![
                message("NewOrderSingle", "D", vec![component_ref("Parties")]),
                message("ExecutionReport", "8", vec![component_ref("Parties")]),
            ]);

            let code = generated(spec).code;

            assert_eq!(code.matches("pub mod parties {").count(), 1);
            assert_eq!(code.matches("pub fn parties(&self)").count(), 2);
        }

        #[test]
        fn group_modules_come_in_order_of_first_appearance() {
            let spec = parties_spec(vec![
                message("PartyDetails", "CG", vec![component_ref("PtysSubGrp")]),
                message("NewOrderSingle", "D", vec![component_ref("Parties")]),
            ]);

            let code = generated(spec).code;

            let ptys_sub_grp = code.find("pub mod ptys_sub_grp {").unwrap();
            let parties = code.find("pub mod parties {").unwrap();
            assert!(ptys_sub_grp < parties);
        }

        #[test]
        fn a_message_group_nests_under_the_message_module() {
            let spec = spec_of(
                vec![message(
                    "Logon",
                    "A",
                    vec![group(384, vec![field_ref(372)])],
                )],
                vec![
                    field("NoMsgTypes", 384, DataType::NumInGroup),
                    field("RefMsgType", 372, DataType::String),
                ],
            );

            let code = generated(spec).code;

            assert!(code.contains(
                "pub mod logon {\n    pub mod msg_types {\n        use super::super::*;\n"
            ));
            assert!(code.contains("self.0.get_group(&logon::msg_types::TABLE, &Self::KNOWN_TAGS)"));
        }

        #[test]
        fn a_group_in_a_group_instance_is_skipped_with_a_warning() {
            let mut spec = parties_spec(vec![message(
                "NewOrderSingle",
                "D",
                vec![component_ref("Parties")],
            )]);
            spec.components = vec![Component {
                name: "Parties".to_owned(),
                members: vec![group(
                    453,
                    vec![field_ref(448), group(802, vec![field_ref(523)])],
                )],
            }];

            let generated = generated(spec);

            assert!(!generated.code.contains("party_sub_ids"));
            assert!(
                generated
                    .code
                    .contains("&[GroupTable::new(Tag(802), Tag(523), &[Tag(523)], &[])]")
            );
            assert_eq!(
                generated.warnings,
                vec![Warning::UnsupportedGroup {
                    context: MemberContext::Component("Parties".to_owned())
                        .group("NoPartyIDs")
                        .group("NoPartySubIDs"),
                }]
            );
        }
    }
}
